# Generated by Django 4.2.7 on 2023-12-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Itens',
        ),
    ]
