# Generated by Django 4.2.7 on 2023-12-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0002_rename_items_itens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id',
            new_name='id_pro',
        ),
    ]
