# Generated by Django 4.2.7 on 2023-12-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0003_rename_itens_produto_rename_id_produto_id_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id_pro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='idade',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_pro',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(null=True),
        ),
    ]
