# Generated by Django 4.2.7 on 2023-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0005_alter_produto_categoria_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_pro',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
