# Generated by Django 4.2.7 on 2023-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0008_alter_produto_codigo_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_pro',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
