# Generated by Django 4.2.7 on 2023-12-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amz', '0009_alter_produto_codigo_pro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-codigo_pro']},
        ),
    ]
